# Setup these variables first
# - DOCKER_USERNAME
# - DOCKER_PASSWORD
# - DOCKER_REGISTRY
# - DISCORD_WEBHOOK_ID
# - DISCORD_WEBHOOK_TOKEN
# - SONAR_HOST
# - SONAR_TOKEN

kind: pipeline
type: kubernetes
name: default

steps:
- name: build-latest
  image: plugins/kaniko
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    registry:
      from_secret: DOCKER_REGISTRY
    repo: glendmaatita/exercise-app
    tags: latest
  when:
    branch: 
    - main
    event: 
    - push

- name: sonarqube-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: SONAR_HOST
    sonar_token:
      from_secret: SONAR_TOKEN
  when:
    branch: 
    - main
    event: 
    - pull_request

# Build by tag
# Need to install Drone Cli first
# Install the Drone CLI
# curl -L https://github.com/drone/drone-cli/releases/latest/download/drone_linux_amd64.tar.gz | tar zx
# sudo install -t /usr/local/bin drone

# Authenticate the Drone CLI
# export DRONE_SERVER=https://drone.bootcamp.onxp.net
# export DRONE_TOKEN=your-drone-token
# to build: drone build create --tag TAG_NAME REPO_NAME
# example: drone build create --tag v1.0.0 onxpnet/exercise-app
- name: build-tag
  image: plugins/kaniko
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    registry:
      from_secret: DOCKER_REGISTRY
    repo: glendmaatita/exercise-app
    tags: 
      - ${TAG_NAME}
  when:
    event:
    - custom

- name: notification
  image: appleboy/drone-discord
  settings:
    webhook_id: 
      from_secret: DISCORD_WEBHOOK_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_TOKEN
    username: DroneCI
    avatar_url: https://cdn.discordapp.com/attachments/892612412014997557/1226805651158601748/Microsoft.png?ex=665590cc&is=66543f4c&hm=caf63d12d5c5ba743970a88edde3ec0798b6cc599ff2570ba584326ad9502594&
    message: >
      {{#success build.status}}
        Build **exercise-app** is *done*. Check on https://drone.bootcamp.onxp.net/onxpnet/exercise-app/{{build.number}} for more details.
      {{else}}
        Build **exercise-app** is *failed*. Check on https://drone.bootcamp.onxp.net/onxpnet/exercise-app/{{build.number}} for more details.
      {{/success}}
