FROM --platform=linux/x86_64 node:20.9.0-bullseye-slim as builder

WORKDIR /opt/app

COPY . .
RUN npm install -g jsdoc
RUN jsdoc .

FROM --platform=linux/x86_64 nginx:latest as runner
COPY --from=builder /opt/app/out /opt/app/out

COPY ./docker/default.conf /etc/nginx/conf.d/default.conf