# Check - 1
name: Main Workflow - Build docker and push to docker hub

on:
  push:
    branches:
      - main

# clone git -> install NodeJS -> 
jobs:
  # build docker image and push to docker hub
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install jest
        run: npm ci

      # run unit test
      - name: Run test
        run: npx jest --coverage

      - name: Check coverage
        run: |
          COVERAGE=$(npx jest --coverage --coverageReporters=text-summary | grep 'All files' | awk '{print $4}' | sed 's/%//')
          if [ "$COVERAGE" -lt 100 ]; then
            echo "Coverage is less than 100%. Exiting."
            exit 1
          fi

      # linting
      # validate docs

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: glendmaatita/exercise-app:latest
  
  # More info: https://github.com/marketplace/actions/aqua-security-trivy
  # DevSecOps: Perform vulnerability scanning
  verify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/glendmaatita/exercise-app:latest'
          format: 'table'
          exit-code: '0' # set 1, if stop the workflow when vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  notify:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        run: |
          curl -v -X POST "${{secrets.DISCORD_WEBHOOKS_URL}}" -H "Content-Type: application/json" -d "{\"content\": \"Build Exercise App on main has been finished. Check this on https://github.com/onxpnet/exercise-app/actions/runs/${{ github.run_id }}\", \"username\": \"github-bot\", \"avatar_url\": \"https://cdn.discordapp.com/attachments/892612412014997557/1226787592725463040/gitlab-logo-600.png?ex=662609fa&is=661394fa&hm=ab695f97e42f571d6d98dd5a9f9fa8db1c295fdf16290489b21430069443ce8b&\"}"
          